### ISSUE TITLE
引入的 icon 会被删除一些数据

### ISSUE THREAD

**Issue by viewweiwu** [ltaoo/umi-plugin-icons#1]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/14287892/167243716-b9fb6442-6d8b-4c51-b273-b9a3855eab49.png">

原本五位数的，现在变成两位数，从而导致显示错误。

```
<svg
    width="10"
    height="5"
    viewBox="0 0 10 5"
    fill="currentColor"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path d="M4.83013 5L0.330079 -2.21732e-06L9.33008 -1.43051e-06L4.83013 5Z" />
  </svg>
```

**Comment by ltaoo** [comment]
hi，不好意思我的文档没写清楚，我们的 `SVG` 是需要符合 `iconfont` 规范的图标，即 1024x1024 画布，具体可以参考 `iconfont` 文档 https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d68c573b2&helptype=draw

其实显示并没有问题，只是太小了看不到。你的图标我放大到 1024 后是能正常展示的，你可以试试

```
<svg width="1024" height="1024" xmlns="http://www.w3.org/2000/svg">
  <path d="m503.83508,760.88886l-444.50492,-493.88886l888.99995,0l-444.49504,493.88886z"/>
</svg>
```

我更新下 `readme` 说明 `SVG` 图标要求，谢谢你的反馈
